apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-instance
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/syangsao/openshift_gitops.git'
    targetRevision: main
    path: operators/odf-instance
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
