apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virt-argocd-access
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["hyperconvergeds"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virt-argocd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virt-argocd-access
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
