apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  annotations:
    MulticloudObjectGatewayProviderMode: "true"
  labels:
    app: noobaa
  name: noobaa
  namespace: openshift-storage
spec:
  affinity: {}
  autoscaler:
    autoscalerType: hpav2
    prometheusNamespace: openshift-monitoring
  bucketLogging: {}
  bucketNotifications:
    enabled: false
  cleanupPolicy: {}
  coreResources:
    limits:
      cpu: "3"
      memory: 4Gi
    requests:
      cpu: "3"
      memory: 4Gi
  dbSpec:
    dbMinVolumeSize: 50Gi
    dbResources:
      limits:
        cpu: "3"
        memory: 4Gi
      requests:
        cpu: "3"
        memory: 4Gi
    dbStorageClass: nfs-csidriver3
    image: registry.redhat.io/rhel9/postgresql-16@sha256:745581a8e045ede5e3aaf30502ef40672e5579bf00155a0031c15c18ebe4d970
  image: registry.redhat.io/odf4/mcg-core-rhel9@sha256:830d232b418552c4a7610c1e0b12a2c03f8c9c821051236d41ac8e4ad1dc06a9
  endpoints:
    maxCount: 10
    minCount: 3
    resources:
      limits:
        cpu: "3"
        memory: 4Gi
      requests:
        cpu: "3"
        memory: 4Gi
  labels:
    monitoring:
      noobaa.io/managedBy: ocs-storagecluster
  loadBalancerSourceSubnets: {}
  pvPoolDefaultStorageClass: nfs-csidriver3
  security:
    kms:
      schedule: '@weekly'
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    operator: Equal
    value: "true"
